# Generated by Django 5.2.12 on 2026-06-24 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_delete_notification'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
    ]
