# Generated by Django 5.2.5 on 2025-08-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('three_d_path', models.FileField(blank=True, null=True, upload_to='products/3d/')),
                ('mtl_file', models.FileField(blank=True, null=True, upload_to='products/mtl/')),
                ('category', models.CharField(choices=[('Tools', 'Tools'), ('Materials', 'Materials'), ('Hardware', 'Hardware'), ('Safety', 'Safety')], max_length=50)),
                ('rating', models.FloatField(default=0.0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
