# Generated by Django 5.2.12 on 2026-06-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_availability_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(blank=True, choices=[('plumber', 'Plumber'), ('electrician', 'Electrician'), ('carpenter', 'Carpenter'), ('mason', 'Mason'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='technician_status',
            field=models.CharField(blank=True, choices=[('pending_approval', 'Pending Approval'), ('payment_pending', 'Payment Pending'), ('active', 'Active')], help_text='Only relevant for technicians: tracks approval & payment state', max_length=20, null=True),
        ),
    ]
