# Generated by Django 5.2.12 on 2026-06-24 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_systemsetting_user_two_fa_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='Unique external reference sent to CamPay', max_length=100, unique=True)),
                ('campay_reference', models.CharField(blank=True, help_text='Transaction reference returned by CamPay', max_length=100, null=True)),
                ('transaction_type', models.CharField(choices=[('order', 'Order Payment'), ('subscription', 'Technician Subscription')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='XAF', max_length=10)),
                ('phone_number', models.CharField(help_text='Payer mobile money phone number (format: 237xxxxxxxxx)', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Successful'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('order_id', models.CharField(blank=True, help_text="Order ID (MongoDB string ID) if transaction_type is 'order'", max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='User initiating the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
